services:
  postgres:
    image: postgres:16
    container_name: salon-explorer-postgres
    environment:
      POSTGRES_DB: salon_explorer
      POSTGRES_USER: salon_user
      POSTGRES_PASSWORD: salon_password
    ports:
      - "5434:5432"
    volumes:
      - salon_explorer_postgres_data:/var/lib/postgresql/data

volumes:
  salon_explorer_postgres_data: