spring.application.name=salonExplorer

spring.datasource.url=jdbc:postgresql://localhost:5434/salon_explorer
spring.datasource.username=salon_user
spring.datasource.password=salon_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

server.port=8080